

all:
   cd chatclient
   nmake
   cd ..
   cd netlib
   nmake
   cd ..
   cd chatclientnet
   nmake
   cd ..
   cd chatserver
   nmake
   cd ..
   cd drvload
   nmake
   cd ..
   cd netdrv
   nmake
   cd ..

dir:
   mkdir ..\..\..\..\bin
   mkdir ..\..\..\..\bin\symbols
   mkdir ..\..\..\lib


clean:
   cd chatclient
   nmake clean
   cd ..
   cd netlib
   nmake clean
   cd ..
   cd chatclientnet
   nmake clean
   cd ..
   cd chatserver
   nmake clean
   cd ..
   cd drvload
   nmake clean
   cd ..
   cd netdrv
   nmake clean
   cd ..
