#ifndef PUBLIC_H
#define PUBLIC_H

#define DEVICE_NAME "YTDevice"
#define DEVICE_PATH L"\\Device\\"DEVICE_NAME
#define DOSDEVICE_PATH L"\\DosDevices\\"DEVICE_NAME
#define FILE_PATH "\\\\.\\"DEVICE_NAME

#define MY_IOCTL_PUSH \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#define MY_IOCTL_POP \
	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)

#endif // PUBLIC_H